version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"
  apt_packages:
    - libosmesa6-dev
    - libgl1-mesa-dev
    - python3-tk
    - pandoc
    - git-restore-mtime
    - xvfb
    - aria2c
  jobs:
    post_install:
      - export DISPLAY=:99.0
      - export PYVISTA_OFF_SCREEN=true
      - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - sleep 3

# Build from the doc/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: requirements_docs.txt
